import type { ComponentCatalog } from "../public/types";

export const componentCatalogEntries = {
	"Layout.Flex": {
		type: "Layout.Flex",
		kind: "layout-flex",
		source: "layout-primitive",
		version: "1.0.0",
		description: "Vertical/horizontal flex container with token-driven spacing.",
		props: {
			direction: {
				type: "enum",
				role: "layout",
				values: ["row", "column"],
				defaultValue: "column",
			},
			gap: { type: "number", role: "layout", tokenRole: "spacing" },
			paddingX: { type: "number", role: "layout", tokenRole: "spacing" },
			paddingY: { type: "number", role: "layout", tokenRole: "spacing" },
			align: {
				type: "enum",
				role: "layout",
				values: ["start", "center", "end", "stretch"],
			},
			justify: {
				type: "enum",
				role: "layout",
				values: ["start", "center", "end", "between"],
			},
		},
	},
	"Layout.Grid": {
		type: "Layout.Grid",
		kind: "layout-grid",
		source: "layout-primitive",
		version: "1.0.0",
		description: "CSS grid container with token-driven spacing.",
		props: {
			columns: { type: "string", role: "layout" },
			rows: { type: "string", role: "layout" },
			gap: { type: "number", role: "layout", tokenRole: "spacing" },
			paddingX: { type: "number", role: "layout", tokenRole: "spacing" },
			paddingY: { type: "number", role: "layout", tokenRole: "spacing" },
			align: {
				type: "enum",
				role: "layout",
				values: ["start", "center", "end", "stretch"],
			},
			justify: {
				type: "enum",
				role: "layout",
				values: ["start", "center", "end", "stretch"],
			},
		},
	},
	PageStack: {
		type: "PageStack",
		kind: "page-stack",
		source: "layout-primitive",
		version: "1.0.0",
		description: "Region inset wrapper. Edge padding + safe-area aware vertical stack.",
		aliases: ["Pagestack", "pagestack", "Default 20/PagestackItemTemplate"],
		props: {
			gap: { type: "number", role: "layout", tokenRole: "spacing" },
			paddingX: { type: "number", role: "layout", tokenRole: "spacing" },
			paddingY: { type: "number", role: "layout", tokenRole: "spacing" },
			itemPaddingX: { type: "number", role: "layout", tokenRole: "spacing" },
			sectionPaddingX: { type: "number", role: "layout", tokenRole: "spacing" },
			sectionGap: { type: "number", role: "layout", tokenRole: "spacing" },
			slotInsetX: { type: "number", role: "layout", tokenRole: "spacing" },
			itemTemplate: {
				type: "enum",
				role: "styleVariant",
				values: ["card-0", "default-20", "plain"],
				defaultValue: "default-20",
			},
			titleMode: {
				type: "enum",
				role: "visibility",
				values: ["hidden", "none", "visible"],
				defaultValue: "none",
			},
		},
	},
	ActionButton: {
		type: "ActionButton",
		kind: "action",
		source: "react-component",
		version: "1.0.0",
		description: "Bottom action rail button backed by @cx/components ActionButton.",
		aliases: ["action-button"],
		props: {
			label: { type: "string", role: "label", required: true },
			variant: {
				type: "enum",
				role: "styleVariant",
				values: ["primary", "secondary", "solid"],
				defaultValue: "primary",
				variantTokens: {
					primary: { surface: "color.surface.brand", text: "color.text.inverse" },
					secondary: { surface: "color.surface.muted", text: "color.text" },
					solid: { surface: "color.surface", text: "color.text", border: "color.border.strong" },
				},
			},
			size: {
				type: "enum",
				role: "layout",
				values: ["xsmall", "small", "medium", "large", "xlarge"],
				defaultValue: "xlarge",
			},
			fullWidth: { type: "boolean", role: "layout", defaultValue: true },
			rightIcon: { type: "node", role: "slot", aiWritable: false },
		},
	},
	AppBar: {
		type: "AppBar",
		kind: "header",
		source: "react-component",
		version: "1.0.0",
		aliases: ["app-bar", "appbar", "AppBarHeaderTopNav"],
		props: {
			title: { type: "string", role: "title" },
			showBack: { type: "boolean", role: "visibility", defaultValue: false },
			showLogo: { type: "boolean", role: "visibility", defaultValue: false },
			rightItem: { type: "node", role: "slot", aiWritable: false },
		},
	},
	Badge: {
		type: "Badge",
		kind: "badge",
		source: "react-component",
		version: "1.0.0",
		aliases: ["badge", "BadgeProductStatus"],
		props: {
			children: { type: "string", role: "content", required: true },
			variant: {
				type: "enum",
				role: "styleVariant",
				values: ["gray", "black", "blue"],
				defaultValue: "gray",
				variantTokens: {
					gray: { surface: "color.surface.muted", text: "color.text" },
					black: { surface: "color.surface.inverse", text: "color.text.inverse" },
					blue: { surface: "color.surface.brand", text: "color.text.inverse" },
				},
			},
		},
	},
	BannerIndicaterMedium: {
		type: "BannerIndicaterMedium",
		kind: "banner-indicator",
		source: "react-component",
		version: "1.0.0",
		description: "Medium banner carousel item with an indicator, matching Figma spelling.",
		aliases: ["BannerIndicatorMedium", "banner-indicator", "banner", "carousel-banner"],
		props: {
			title: { type: "string", role: "title", required: true },
			description: { type: "string", role: "description" },
			imageUrl: { type: "string", role: "data" },
			current: { type: "number", role: "state", defaultValue: 1 },
			total: { type: "number", role: "state", defaultValue: 1 },
		},
	},
	BottomNavigation: {
		type: "BottomNavigation",
		source: "react-component",
		version: "1.0.0",
		props: {
			items: { type: "array", role: "data", required: true },
			activeKey: { type: "string", role: "state", required: true },
		},
	},
	ButtonCloseItem: {
		type: "ButtonCloseItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "ButtonCloseItem (Figma part / standalone:false).",
		aliases: ["button-close-item"],
		props: {},
	},
	ButtonListOrder: {
		type: "ButtonListOrder",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "ButtonListOrder (Figma part / standalone:false).",
		aliases: ["button-list-order"],
		props: { label: { type: "string", role: "label" } },
	},
	ButtonMoreProductItem: {
		type: "ButtonMoreProductItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "ButtonMoreProductItem (Figma part / standalone:false).",
		aliases: ["button-more-product-item"],
		props: { label: { type: "string", role: "label" }, logoColor: { type: "string", role: "value" } , logo: { type: "node", role: "slot" } },
	},
	ChipImageItem: {
		type: "ChipImageItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "ChipImageItem (Figma part / standalone:false).",
		aliases: ["chip-image-item"],
		props: { label: { type: "string", role: "label" }, selected: { type: "boolean", role: "state", defaultValue: false } , icon: { type: "node", role: "slot" } },
	},
	CardContentsItem: {
		type: "CardContentsItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "CardContentsItem (Figma part / standalone:false).",
		aliases: ["card-contents-item"],
		props: { type: { type: "string", role: "styleVariant", values: ["List","Barcode","Ai"], defaultValue: "List" }, imageSrc: { type: "string", role: "slot" }, title: { type: "string", role: "title" }, subtitle: { type: "string", role: "description" } , daysLeft: { type: "string", role: "content" }, buttonLabel: { type: "string", role: "content" }, aiText: { type: "string", role: "content" }, barcodeNum: { type: "string", role: "content" } },
	},
	CardSectionTitle: {
		type: "CardSectionTitle",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "CardSectionTitle (Figma part / standalone:false).",
		aliases: ["card-section-title"],
		props: { title: { type: "string", role: "title" }, children: { type: "node", role: "content" } },
	},
	BadgeHome: {
		type: "BadgeHome",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "BadgeHome (Figma part / standalone:false).",
		aliases: ["badge-home"],
		props: { label: { type: "string", role: "label" } },
	},
	BadgeIcon: {
		type: "BadgeIcon",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "BadgeIcon (Figma part / standalone:false).",
		aliases: ["badge-icon"],
		props: { label: { type: "string", role: "label" }, subLabel: { type: "string", role: "description" } , icon: { type: "node", role: "slot" } },
	},
	Indicator: {
		type: "Indicator",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "Indicator (Figma part / standalone:false).",
		aliases: ["indicator"],
		props: { count: { type: "number", role: "value" }, activeIndex: { type: "number", role: "value" } },
	},
	TitleSectionLeftItem: {
		type: "TitleSectionLeftItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "TitleSectionLeftItem (Figma part / standalone:false).",
		aliases: ["title-section-left-item"],
		props: { type: { type: "string", role: "styleVariant", values: ["Text","Icon","Badge"], defaultValue: "Text" }, count: { type: "string", role: "value" } , badge: { type: "node", role: "slot" } },
	},
	TitleSectionRightItem: {
		type: "TitleSectionRightItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "TitleSectionRightItem (Figma part / standalone:false).",
		aliases: ["title-section-right-item"],
		props: { type: { type: "string", role: "styleVariant", values: ["Icon","TextButton","TextItemButton","ButtonListOrder","Text"], defaultValue: "TextButton" }, label: { type: "string", role: "label" }, subText: { type: "string", role: "description" } , highlight: { type: "string", role: "content" } },
	},
	TitleContentsRightItem: {
		type: "TitleContentsRightItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "TitleContentsRightItem (Figma part / standalone:false).",
		aliases: ["title-contents-right-item"],
		props: { type: { type: "string", role: "styleVariant", values: ["Icon","Button"], defaultValue: "Icon" }, label: { type: "string", role: "label" } },
	},
	LeftItem: {
		type: "LeftItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "LeftItem (Figma part / standalone:false).",
		aliases: ["left-item"],
		props: { type: { type: "string", role: "styleVariant", values: ["Ai","Ai+Gift"], defaultValue: "Ai" }, color: { type: "string", role: "value" } },
	},
	RightItem: {
		type: "RightItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "RightItem (Figma part / standalone:false).",
		aliases: ["right-item"],
		props: { type: { type: "string", role: "styleVariant", values: ["Text","TextButton","Icon","BadgeLevel"], defaultValue: "Icon" }, label: { type: "string", role: "label" } },
	},
	TitleBottomSheet: {
		type: "TitleBottomSheet",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "TitleBottomSheet (Figma node 9412:12082 / BS no.0 시트 헤더 — AppBar의 BS 대응, writer 단독 주입 크롬).",
		aliases: ["title-bottom-sheet"],
		props: { title: { type: "string", role: "title" }, subText: { type: "string", role: "description" }, subTextHighlight: { type: "string", role: "content" } },
	},
	Tooltip: {
		type: "Tooltip",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "Tooltip (Figma part / standalone:false).",
		aliases: ["tooltip"],
		props: { label: { type: "string", role: "label" }, tailPosition: { type: "string", role: "styleVariant", values: ["Left","Center","Right"], defaultValue: "Center" } },
	},
	ThumbnailItem: {
		type: "ThumbnailItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "ThumbnailItem (Figma part / standalone:false).",
		aliases: ["thumbnail-item"],
		props: { size: { type: "string", role: "styleVariant", values: ["40","64","160","182","movie"], defaultValue: "64" }, src: { type: "string", role: "slot" } , alt: { type: "string", role: "content" } },
	},
	ThumbnailLogoItem: {
		type: "ThumbnailLogoItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "ThumbnailLogoItem (Figma part / standalone:false).",
		aliases: ["thumbnail-logo-item"],
		props: { src: { type: "string", role: "slot" }, bgColor: { type: "string", role: "value" } , logo: { type: "node", role: "slot" } },
	},
	ProductInfoHorizontal: {
		type: "ProductInfoHorizontal",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "ProductInfoHorizontal (Figma part / standalone:false).",
		aliases: ["product-info-horizontal"],
		props: { subtitle: { type: "string", role: "description" }, mainText: { type: "string", role: "title" }, subText: { type: "string", role: "description" } , discountLabel: { type: "string", role: "content" }, discountAmount: { type: "string", role: "value" } },
	},
	ProductInfoVertical: {
		type: "ProductInfoVertical",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "ProductInfoVertical (Figma part / standalone:false).",
		aliases: ["product-info-vertical"],
		props: { textSub: { type: "string", role: "description" }, textMain: { type: "string", role: "title" }, price: { type: "string", role: "value" }, discountRate: { type: "string", role: "value" } , originalPrice: { type: "string", role: "value" }, priceSuffix: { type: "string", role: "value" } },
	},
	PaymentLogoItem: {
		type: "PaymentLogoItem",
		kind: "part",
		source: "react-component",
		version: "1.0.0",
		description: "PaymentLogoItem (Figma part / standalone:false).",
		aliases: ["payment-logo-item"],
		props: { src: { type: "string", role: "slot" } , bgColor: { type: "string", role: "data" } },
	},
	ButtonMore: {
		type: "ButtonMore",
		kind: "button",
		source: "react-component",
		version: "1.0.0",
		description: "ButtonMore (Figma 9638-78644 기반).",
		aliases: ["button-more"],
		props: { label: { type: "string", role: "label" } },
	},
	ButtonMoreProduct: {
		type: "ButtonMoreProduct",
		kind: "button",
		source: "react-component",
		version: "1.0.0",
		description: "ButtonMoreProduct (Figma 9638-78644 기반).",
		aliases: ["button-more-product"],
		props: { label: { type: "string", role: "label" }, logoColor: { type: "string", role: "value" } , logo: { type: "node", role: "slot" } },
	},
	UnderlineTab: {
		type: "UnderlineTab",
		kind: "tabs",
		source: "react-component",
		version: "1.0.0",
		description: "UnderlineTab (Figma 9638-78644 기반).",
		aliases: ["underline-tab"],
		props: { items: { type: "array", role: "data" }, activeIndex: { type: "number", role: "state", defaultValue: 0 } },
	},
	TitleContents: {
		type: "TitleContents",
		kind: "title",
		source: "react-component",
		version: "1.0.0",
		description: "TitleContents (Figma 9638-78644 기반).",
		aliases: ["title-contents"],
		props: { title: { type: "string", role: "title" }, showButton: { type: "boolean", role: "visibility", defaultValue: false }, expanded: { type: "boolean", role: "state", defaultValue: true } },
	},
	PayProductListItem: {
		type: "PayProductListItem",
		kind: "item",
		source: "react-component",
		version: "1.0.0",
		description: "PayProductListItem (Figma 9638-78644 기반).",
		aliases: ["pay-product-list-item"],
		props: { type: { type: "string", role: "styleVariant", values: ["Pay","Cart"], defaultValue: "Pay" }, brand: { type: "string", role: "description" }, productName: { type: "string", role: "title" }, thumbnailSrc: { type: "string", role: "slot" }, priceRows: { type: "array", role: "data" }, totalPrice: { type: "string", role: "value" } , showBox: { type: "boolean", role: "visibility" }, boxOption: { type: "string", role: "content" }, totalLabel: { type: "string", role: "value" }, totalPeriod: { type: "string", role: "value" }, showChangeLink: { type: "boolean", role: "visibility" } },
	},
	OptionListItem: {
		type: "OptionListItem",
		kind: "option-item",
		source: "react-component",
		version: "1.0.0",
		description: "OptionListItem (Figma 9638-78644 기반).",
		aliases: ["option-list-item"],
		props: { type: { type: "string", role: "styleVariant", values: ["Module","List"], defaultValue: "List" }, label: { type: "string", role: "label" }, value: { type: "string", role: "value" }, selected: { type: "boolean", role: "state", defaultValue: false } , subText: { type: "string", role: "description" }, unit: { type: "string", role: "value" }, badge: { type: "string", role: "content" }, price: { type: "string", role: "value" }, showColorChip: { type: "boolean", role: "visibility" }, colorChip: { type: "string", role: "data" } },
	},
	Button: {
		type: "Button",
		kind: "action",
		source: "react-component",
		version: "1.0.0",
		aliases: ["button"],
		props: {
			label: { type: "string", role: "label", required: true },
			variant: {
				type: "enum",
				role: "styleVariant",
				values: ["primary", "secondary", "solid"],
				defaultValue: "primary",
				variantTokens: {
					primary: { surface: "color.surface.brand", text: "color.text.inverse" },
					secondary: { surface: "color.surface.muted", text: "color.text" },
					solid: { surface: "color.surface", text: "color.text", border: "color.border.strong" },
				},
			},
			size: {
				type: "enum",
				role: "layout",
				values: ["xsmall", "small", "medium", "large", "xlarge"],
				defaultValue: "medium",
			},
			fullWidth: { type: "boolean", role: "layout", defaultValue: false },
			rightIcon: { type: "node", role: "slot", aiWritable: false },
			type: { type: "string", role: "data" },
		},
	},
	Callout: {
		type: "Callout",
		kind: "section-message",
		source: "react-component",
		version: "1.0.0",
		props: {
			title: { type: "string", role: "title" },
			children: { type: "string", role: "content", required: true },
		},
	},
	CardContentsFilled: {
		type: "CardContentsFilled",
		kind: "card-contents",
		source: "react-component",
		version: "1.0.0",
		description: "Filled content card with a slot-like text surface.",
		aliases: ["card-contents-filled", "card-text"],
		props: {
			title: { type: "string", role: "title" },
			description: { type: "string", role: "description" },
		},
	},
	AccordionProductInfo: {
		type: "AccordionProductInfo",
		kind: "accordion",
		source: "react-component",
		version: "1.0.0",
		description: "Subscription product info accordion (Default/Open).",
		aliases: ["accordion-product-info"],
		props: {
			states: { type: "string", role: "state", values: ["Default", "Open"], defaultValue: "Default" },
			logoSrc: { type: "string", role: "slot" },
			brandName: { type: "string", role: "description" },
			productName: { type: "string", role: "title" },
			children: { type: "node", role: "content" },
			logoBg: { type: "string", role: "data" },
		},
	},
	BannerSearch: {
		type: "BannerSearch",
		kind: "banner",
		source: "react-component",
		version: "1.0.0",
		description: "Search-screen visual banner.",
		aliases: ["banner-search"],
		props: { image: { type: "string", role: "slot" } },
	},
	BannerShop: {
		type: "BannerShop",
		kind: "banner",
		source: "react-component",
		version: "1.0.0",
		description: "Shop top promotion banner.",
		aliases: ["banner-shop"],
		props: {
			subtitle: { type: "string", role: "description" },
			titleLine1: { type: "string", role: "title" },
			titleLine2: { type: "string", role: "title" },
			image: { type: "string", role: "slot" },
		},
	},
	CarouselProduct: {
		type: "CarouselProduct",
		kind: "carousel",
		source: "react-component",
		version: "1.0.0",
		description: "Horizontal-scroll product card.",
		aliases: ["carousel-product"],
		props: {
			imageSrc: { type: "string", role: "slot" },
			subTitle: { type: "string", role: "description" },
			title: { type: "string", role: "title" },
			originalPrice: { type: "string", role: "value" },
			discountRate: { type: "string", role: "value" },
			price: { type: "string", role: "value" },
			priceUnit: { type: "string", role: "value" },
			badges: { type: "array", role: "data" },
		},
	},
	CarouselProductText: {
		type: "CarouselProductText",
		kind: "carousel",
		source: "react-component",
		version: "1.0.0",
		description: "Text-focused product carousel card.",
		aliases: ["carousel-product-text"],
		props: {
			subtitle: { type: "string", role: "description" },
			title: { type: "string", role: "title" },
			description: { type: "string", role: "description" },
			logoSrc: { type: "string", role: "slot" },
			badges: { type: "array", role: "data" },
		},
	},
	HomeCardCarousel: {
		type: "HomeCardCarousel",
		kind: "carousel",
		source: "react-component",
		version: "1.0.0",
		description: "Home card-carousel section wrapper.",
		aliases: ["home-card-carousel"],
		props: {
			subtitle: { type: "string", role: "description" },
			titleLine1: { type: "string", role: "title" },
			titleLine2: { type: "string", role: "title" },
			children: { type: "node", role: "content" },
		},
	},
	Icon: {
		type: "Icon",
		kind: "icon",
		source: "react-component",
		version: "1.0.0",
		description: "System icon (placeholder; SVG set pending).",
		aliases: ["icon"],
		props: {
			name: { type: "string", role: "slot" },
			size: { type: "number", role: "value", defaultValue: 24 },
			color: { type: "string", role: "value" },
		},
	},
	Thumbnail: {
		type: "Thumbnail",
		kind: "thumbnail",
		source: "react-component",
		version: "1.0.0",
		description: "Product/Brand cover image with indicator and brand info.",
		aliases: ["thumbnail"],
		props: {
			type: { type: "string", role: "styleVariant", values: ["Product", "Brand"], defaultValue: "Product" },
			imageSrc: { type: "string", role: "slot" },
			brandName: { type: "string", role: "title" },
			brandDesc: { type: "string", role: "description" },
			likeCount: { type: "string", role: "value" },
			badges: { type: "array", role: "data" },
			totalDots: { type: "number", role: "value" },
			activeDotIndex: { type: "number", role: "value" },
			category: { type: "string", role: "content" },
		},
	},
	ButtonSection: {
		type: "ButtonSection",
		kind: "button",
		source: "react-component",
		version: "1.0.0",
		description: "Home 2-up icon+label shortcut buttons.",
		aliases: ["button-section"],
		props: {
			leftIcon: { type: "string", role: "slot" },
			leftLabel: { type: "string", role: "label" },
			rightIcon: { type: "string", role: "slot" },
			rightLabel: { type: "string", role: "label" },
		},
	},
	BannerBenefit: {
		type: "BannerBenefit",
		kind: "banner",
		source: "react-component",
		version: "1.0.0",
		description: "Card benefit emphasis banner.",
		aliases: ["banner-benefit"],
		props: { text: { type: "string", role: "description" }, image: { type: "string", role: "slot" } },
	},
	BannerHorizontalSmall: {
		type: "BannerHorizontalSmall",
		kind: "banner",
		source: "react-component",
		version: "1.0.0",
		description: "Small horizontal banner with title/subtitle and indicator.",
		aliases: ["banner-horizontal-small"],
		props: {
			title: { type: "string", role: "title" },
			subtitle: { type: "string", role: "description" },
			showIndicator: { type: "boolean", role: "visibility", defaultValue: true },
			totalCount: { type: "number", role: "value" },
			activeIndex: { type: "number", role: "value" },
			image: { type: "string", role: "slot" },
		},
	},
	ListProductVertical: {
		type: "ListProductVertical",
		kind: "list-product",
		source: "react-component",
		version: "1.0.0",
		description: "Vertical single product card with image and price.",
		aliases: ["list-product-vertical"],
		props: {
			imageSrc: { type: "string", role: "slot" },
			subTitle: { type: "string", role: "description" },
			title: { type: "string", role: "title" },
			discountRate: { type: "string", role: "value" },
			price: { type: "string", role: "value" },
			priceUnit: { type: "string", role: "value" },
			badges: { type: "array", role: "data" },
			originalPrice: { type: "string", role: "value" },
		},
	},
	PopupActionButton: {
		type: "PopupActionButton",
		kind: "button-group",
		source: "react-component",
		version: "1.0.0",
		description: "Popup footer decision buttons (1 or 2).",
		aliases: ["popup-action-button"],
		props: {
			primaryLabel: { type: "string", role: "label" },
			secondaryLabel: { type: "string", role: "label" },
		},
	},
	Sheet: {
		type: "Sheet",
		kind: "sheet",
		source: "react-component",
		version: "1.0.0",
		description: "Mini sheet summarizing a selected product.",
		aliases: ["sheet"],
		props: {
			logoSrc: { type: "string", role: "slot" },
			productName: { type: "string", role: "title" },
			price: { type: "string", role: "value" },
			priceUnit: { type: "string", role: "value" },
			priceNote: { type: "string", role: "value" },
		},
	},
	ThumbnailSmall: {
		type: "ThumbnailSmall",
		kind: "thumbnail",
		source: "react-component",
		version: "1.0.0",
		description: "Small thumbnail with logo overlay.",
		aliases: ["thumbnail-small"],
		props: {
			src: { type: "string", role: "slot" },
			image: { type: "node", role: "slot" },
			logo: { type: "node", role: "slot" },
		},
	},
	TitleMain: {
		type: "TitleMain",
		kind: "title",
		source: "react-component",
		version: "1.0.0",
		description: "Large top page-title header (Complete/Search).",
		aliases: ["title-main"],
		props: {
			type: { type: "string", role: "styleVariant", values: ["Complete", "Search"], defaultValue: "Complete" },
			title: { type: "string", role: "title" },
			subText: { type: "string", role: "description" },
			chipSrc: { type: "string", role: "slot" },
			deviceName: { type: "string", role: "content" },
			indicatorCount: { type: "number", role: "data" },
			indicatorActiveIndex: { type: "number", role: "data" },
		},
	},
	ButtonItem: {
		type: "ButtonItem",
		kind: "button",
		source: "react-component",
		version: "1.0.0",
		description: "Section-trailing auxiliary text button.",
		aliases: ["button-item"],
		props: { label: { type: "string", role: "label" } },
	},
	CardContentsLine: {
		type: "CardContentsLine",
		kind: "card-contents",
		source: "react-component",
		version: "1.0.0",
		description: "Bordered content card for grouping without emphasis.",
		aliases: ["card-contents-line"],
		props: { children: { type: "node", role: "content" } },
	},
	CardSection: {
		type: "CardSection",
		kind: "card-section",
		source: "react-component",
		version: "1.0.0",
		description: "Container card grouping related content as a section.",
		aliases: ["card-section"],
		props: { children: { type: "node", role: "content" } },
	},
	Pagestack: {
		type: "Pagestack",
		kind: "pagestack",
		source: "react-component",
		version: "1.0.0",
		description: "Vertical stack wrapper for ordered item cards.",
		aliases: ["pagestack"],
		props: {
			title: { type: "string", role: "title" },
			showTitle: { type: "boolean", role: "visibility", defaultValue: true },
			children: { type: "node", role: "content" },
		},
	},
	PagestackItemCard: {
		type: "PagestackItemCard",
		kind: "pagestack-item",
		source: "react-component",
		version: "1.0.0",
		description: "Card-style single item inside a Pagestack.",
		aliases: ["pagestack-item-card"],
		props: { children: { type: "node", role: "content" } },
	},
	PagestackItemDefault: {
		type: "PagestackItemDefault",
		kind: "pagestack-item",
		source: "react-component",
		version: "1.0.0",
		description: "Default list-row single item inside a Pagestack.",
		aliases: ["pagestack-item-default"],
		props: { children: { type: "node", role: "content" } },
	},
	Pin: {
		type: "Pin",
		kind: "badge",
		source: "react-component",
		version: "1.0.0",
		description: "Numbered teardrop map pin.",
		aliases: ["pin"],
		props: {
			number: { type: "string", role: "value" },
			color: { type: "string", role: "value" },
		},
	},
	Spacing: {
		type: "Spacing",
		kind: "separator",
		source: "react-component",
		version: "1.0.0",
		description: "Vertical spacing layout element.",
		aliases: ["spacing"],
		props: { size: { type: "number", role: "value", defaultValue: 8 } },
	},
	CardText: {
		type: "CardText",
		kind: "card-text",
		source: "react-component",
		version: "1.0.0",
		description: "Neutral text card with title and body description (no emphasis background).",
		aliases: ["card-text-card"],
		props: {
			title: { type: "string", role: "title" },
			description: { type: "string", role: "description" },
			body: { type: "string", role: "description" },
		},
	},
	ButtonTextUnderline: {
		type: "ButtonTextUnderline",
		kind: "button",
		source: "react-component",
		version: "1.0.0",
		description: "Underlined inline text link button.",
		aliases: ["button-text-underline"],
		props: {
			label: { type: "string", role: "label", required: true },
			color: { type: "string", role: "value" },
		},
	},
	CardInfo: {
		type: "CardInfo",
		kind: "card-info",
		source: "react-component",
		version: "1.0.0",
		description: "Brand benefit (logo+text+badges) or map place (pin+text+button) info card. 2 types.",
		aliases: ["card-info"],
		props: {
			type: { type: "string", role: "styleVariant", values: ["Brand", "Place"], defaultValue: "Brand" },
			label: { type: "string", role: "label" },
			title: { type: "string", role: "title" },
			subtitle: { type: "string", role: "description" },
			badge: { type: "string", role: "slot" },
			badges: { type: "array", role: "data" },
			image: { type: "string", role: "slot" },
			logoSrc: { type: "string", role: "slot" },
			logoColor: { type: "string", role: "value" },
			pinNumber: { type: "string", role: "value" },
			distance: { type: "string", role: "value" },
			placeName: { type: "string", role: "title" },
			actionLabel: { type: "string", role: "label" },
		},
	},
	PaymentList: {
		type: "PaymentList",
		kind: "payment-list",
		source: "react-component",
		version: "1.0.0",
		description: "Payment method row with radio, logo, label, badge and optional detail card.",
		aliases: ["payment-list"],
		props: {
			label: { type: "string", role: "title" },
			badge: { type: "string", role: "slot" },
			showLogo: { type: "boolean", role: "visibility", defaultValue: true },
			logoSrc: { type: "string", role: "slot" },
			image: { type: "string", role: "slot" },
			showCard: { type: "boolean", role: "visibility", defaultValue: false },
			cardTitle: { type: "string", role: "title" },
			cardTitleHighlight: { type: "string", role: "label" },
			cardSubText: { type: "string", role: "description" },
			selected: { type: "boolean", role: "state", defaultValue: false },
		},
	},
	CardSummary: {
		type: "CardSummary",
		kind: "card-summary",
		source: "react-component",
		version: "1.0.0",
		description: "Summary card for product, rating, price, or calculation sections.",
		aliases: ["card-summary", "CardSummaryProductSummary", "Local_Summary"],
		props: {
			title: { type: "string", role: "title", required: true },
			subText: { type: "string", role: "description" },
			rightText: { type: "string", role: "value" },
			items: { type: "array", role: "data" },
			buttonLabel: { type: "string", role: "label" },
		},
	},
	Accordion: {
		type: "Accordion",
		kind: "accordion",
		source: "renderer-composite",
		version: "1.0.0",
		aliases: ["accordion"],
		props: {
			title: { type: "string", role: "title", required: true },
			description: { type: "string", role: "description" },
			expanded: { type: "boolean", role: "state", defaultValue: false },
		},
	},
	AccordionNoticeInfo: {
		type: "AccordionNoticeInfo",
		kind: "accordion-info",
		source: "react-component",
		version: "1.0.0",
		description: "Notice accordion for PRDD detail/spec information sections.",
		aliases: ["accordion-notice-info", "AccordionList", "faq-accordion", "notice-accordion"],
		props: {
			title: { type: "string", role: "title", required: true },
			description: { type: "string", role: "description" },
			expanded: { type: "boolean", role: "state", defaultValue: false },
		},
	},
	AccordionPriceInfo: {
		type: "AccordionPriceInfo",
		kind: "accordion-info",
		source: "react-component",
		version: "1.0.0",
		description: "Price accordion for PRDD subsidy/price comparison sections.",
		aliases: ["accordion-price-info"],
		props: {
			title: { type: "string", role: "title", required: true },
			description: { type: "string", role: "description" },
			priceText: { type: "string", role: "value" },
			expanded: { type: "boolean", role: "state", defaultValue: false },
		},
	},
	BannerHorizontalMedium: {
		type: "BannerHorizontalMedium",
		kind: "banner",
		source: "react-component",
		version: "1.0.0",
		description: "Medium horizontal banner with title/subtitle over image and slide indicator.",
		aliases: ["banner-horizontal-medium"],
		props: {
			title: { type: "string", role: "title" },
			subtitle: { type: "string", role: "description" },
			showSubtitle: { type: "boolean", role: "visibility", defaultValue: true },
			showIndicator: { type: "boolean", role: "visibility", defaultValue: true },
			totalCount: { type: "number", role: "value" },
			activeIndex: { type: "number", role: "value" },
			image: { type: "string", role: "slot" },
		},
	},
	Radio: {
		type: "Radio",
		kind: "radio",
		source: "react-component",
		version: "1.0.0",
		description: "Single radio item with label (RadioText).",
		aliases: ["radio"],
		props: {
			label: { type: "string", role: "label", required: true },
			checked: { type: "boolean", role: "state", defaultValue: false },
		},
	},
	Checkbox: {
		type: "Checkbox",
		kind: "checkbox",
		source: "renderer-composite",
		version: "1.0.0",
		description: "Checkbox item rendered through @cx/components ListSelected checkbox mode.",
		aliases: ["checkbox"],
		props: {
			label: { type: "string", role: "label", required: true },
			checked: { type: "boolean", role: "state", defaultValue: false },
			variant: {
				type: "enum",
				role: "styleVariant",
				values: ["small", "medium"],
				defaultValue: "medium",
			},
		},
	},
	Chip: {
		type: "Chip",
		source: "react-component",
		version: "1.0.0",
		description: "Selectable horizontal filter chip item.",
		aliases: ["chip", "filter-chip", "ChipFilter", "Local_Chips"],
		props: {
			children: { type: "string", role: "content", required: true },
			selected: { type: "boolean", role: "state", defaultValue: false },
		},
	},
	Dialog: {
		type: "Dialog",
		kind: "dialog",
		source: "react-component",
		version: "1.0.0",
		description: "Modal dialog with title, optional subtext, content slot, and two action buttons (Figma node 50982:21648).",
		aliases: ["dialog", "modal"],
		props: {
			title: { type: "string", role: "title" },
			subText: { type: "string", role: "description" },
			showSubText: { type: "boolean", role: "visibility", defaultValue: true },
			showContents: { type: "boolean", role: "visibility", defaultValue: true },
			primaryLabel: { type: "string", role: "label", defaultValue: "확인" },
			secondaryLabel: { type: "string", role: "label", defaultValue: "취소" },
			children: { type: "node", role: "content" },
		},
	},
	Divider: {
		type: "Divider",
		kind: "divider",
		source: "react-component",
		version: "1.0.0",
		aliases: ["divider", "section-divider", "content-divider"],
		props: {
			type: {
				type: "enum",
				role: "styleVariant",
				values: ["contents", "section"],
				defaultValue: "contents",
				variantTokens: {
					contents: { border: "color.border.subtle" },
					section: { border: "color.border.strong" },
				},
			},
		},
	},
	Footer: {
		type: "Footer",
		kind: "footer",
		source: "react-component",
		version: "1.0.0",
		description: "Low-emphasis legal/help footer for detail screens.",
		aliases: ["footer", "FooterLegal", "legal-footer"],
		props: {
			title: { type: "string", role: "title" },
			description: { type: "string", role: "description" },
			links: { type: "array", role: "data" },
		},
	},
	FilterSorting: {
		type: "FilterSorting",
		kind: "filter-sorting",
		source: "react-component",
		version: "1.0.0",
		description: "List result count, filter, and sort control row for browse screens.",
		aliases: ["filter-sorting", "filter-sort", "FilterSort", "SortFilter"],
		props: {
			countLabel: { type: "string", role: "label", defaultValue: "전체 0개" },
			filterLabel: { type: "string", role: "label", defaultValue: "필터" },
			sortLabel: { type: "string", role: "label", defaultValue: "추천순" },
			showFilter: { type: "boolean", role: "visibility", defaultValue: true },
			showSort: { type: "boolean", role: "visibility", defaultValue: true },
			activeFilterCount: { type: "number", role: "state", defaultValue: 0 },
			showDivider: { type: "boolean", role: "visibility" },
		},
	},
	HeaderBase: {
		type: "HeaderBase",
		kind: "header",
		source: "renderer-composite",
		version: "1.0.0",
		description: "Renderer header node mapped to AppBar.",
		aliases: ["TopNavigation", "top-navigation"],
		props: {
			titleContent: { type: "string", role: "title" },
			titleSize: { type: "string", role: "styleVariant" },
			showBackButton: { type: "boolean", role: "visibility", defaultValue: true },
			showLogo: { type: "boolean", role: "visibility", defaultValue: false },
		},
	},
	InfoTextList: {
		type: "InfoTextList",
		kind: "list-cell",
		source: "react-component",
		version: "1.0.0",
		description: "Text list row with title, category/date, optional badge, or right-side value.",
		aliases: ["info-text-list", "InfoTextListDefault", "InfoTextListWithBadge", "Local_ListInfo"],
		props: {
			title: { type: "string", role: "title" },
			category: { type: "string", role: "description" },
			date: { type: "string", role: "data" },
			badge: { type: "string", role: "styleVariant" },
			rightText: { type: "string", role: "value" },
		},
	},
	LegalText: {
		type: "LegalText",
		kind: "legal-text",
		source: "react-component",
		version: "1.0.0",
		description: "Fine print list for product legal notices.",
		aliases: ["legal-text", "LegalNotice", "legal-notice"],
		props: {
			title: { type: "string", role: "title" },
			items: { type: "array", role: "data", required: true },
		},
	},
	ListCell: {
		type: "ListCell",
		kind: "list-cell",
		source: "renderer-composite",
		version: "1.0.0",
		aliases: ["list-cell"],
		props: {
			title: { type: "string", role: "title", required: true },
			description: { type: "string", role: "description" },
			required: { type: "boolean", role: "state" },
			checked: { type: "boolean", role: "state" },
		},
	},
	Coupon: {
		type: "Coupon",
		kind: "coupon",
		source: "react-component",
		version: "1.0.0",
		description: "Coupon benefit card for commerce detail and brand benefit screens.",
		aliases: ["coupon", "Coupon", "Local_Coupon", "coupon-benefit"],
		props: {
			title: { type: "string", role: "title", defaultValue: "혜택 쿠폰" },
			description: { type: "string", role: "description" },
			benefitText: { type: "string", role: "value", defaultValue: "쿠폰 혜택 제공" },
			conditionText: { type: "string", role: "description" },
			ctaLabel: { type: "string", role: "label", defaultValue: "쿠폰 받기" },
			disabled: { type: "boolean", role: "state", defaultValue: false },
		},
	},
	ListProductHorizontal: {
		type: "ListProductHorizontal",
		kind: "product-card",
		source: "react-component",
		version: "1.0.0",
		description: "Horizontal product card row for SKT card-list browse screens.",
		aliases: ["list-product-horizontal", "product-horizontal-card", "horizontal-product-card"],
		props: {
			title: { type: "string", role: "title", required: true },
			brand: { type: "string", role: "label" },
			description: { type: "string", role: "description" },
			price: { type: "string", role: "value" },
			originalPrice: { type: "string", role: "value" },
			discountRate: { type: "string", role: "value" },
			imageUrl: { type: "string", role: "data" },
			imageAlt: { type: "string", role: "description" },
			badges: { type: "array", role: "data" },
			meta: { type: "string", role: "data" },
			benefitText: { type: "string", role: "description" },
			ctaLabel: { type: "string", role: "label" },
		},
	},
	ListProductRow: {
		type: "ListProductRow",
		kind: "product-card",
		source: "react-component",
		version: "1.0.0",
		description: "Large product row card for SKT device/subscription browse screens.",
		aliases: ["list-product-row", "product-row-card", "row-product-card"],
		props: {
			title: { type: "string", role: "title", required: true },
			brand: { type: "string", role: "label" },
			description: { type: "string", role: "description" },
			price: { type: "string", role: "value" },
			originalPrice: { type: "string", role: "value" },
			discountRate: { type: "string", role: "value" },
			imageUrl: { type: "string", role: "data" },
			imageAlt: { type: "string", role: "description" },
			badges: { type: "array", role: "data" },
			specs: { type: "array", role: "data" },
			benefitText: { type: "string", role: "description" },
			ctaLabel: { type: "string", role: "label" },
		},
	},
	ListSelected: {
		type: "ListSelected",
		kind: "list-cell",
		source: "react-component",
		version: "1.0.0",
		aliases: ["list-selected"],
		props: {
			type: {
				type: "enum",
				role: "styleVariant",
				values: ["radio", "checkbox"],
				defaultValue: "radio",
			},
			label: { type: "string", role: "label", required: true },
			price: { type: "string", role: "value" },
			buttonLabel: { type: "string", role: "label" },
			checked: { type: "boolean", role: "state", defaultValue: false },
			showPrice: { type: "boolean", role: "visibility", defaultValue: true },
			showButton: { type: "boolean", role: "visibility", defaultValue: true },
		},
	},
	ListSelectedRightItem: {
		type: "ListSelectedRightItem",
		kind: "list-cell",
		source: "react-component",
		version: "1.0.0",
		props: {
			label: { type: "string", role: "label", required: true },
			type: {
				type: "enum",
				role: "styleVariant",
				values: ["buttonXsmallSolid"],
				defaultValue: "buttonXsmallSolid",
			},
		},
	},
	ListText: {
		type: "ListText",
		kind: "list-cell",
		source: "react-component",
		version: "1.0.0",
		aliases: ["list-text", "ListTextProductInfo"],
		props: {
			table: {
				type: "enum",
				role: "styleVariant",
				values: ["off", "on", "dot", "firstTitle", "secondTitle"],
				defaultValue: "off",
			},
			title: { type: "string", role: "title" },
			subText: { type: "string", role: "description" },
			price: { type: "string", role: "value" },
			showRightItem: { type: "boolean", role: "visibility", defaultValue: true },
		},
	},
	MapBlock: {
		type: "MapBlock",
		kind: "map",
		source: "react-component",
		version: "1.0.0",
		description: "Map placeholder block for nearby store sections.",
		aliases: ["Map", "map", "map-block"],
		props: {
			title: { type: "string", role: "title" },
			address: { type: "string", role: "description" },
		},
	},
	OptionCard: {
		type: "OptionCard",
		kind: "option-card",
		source: "react-component",
		version: "1.0.0",
		description: "Selectable product option card for commerce detail patterns.",
		aliases: ["option-card", "select-card", "OptionSelectCard"],
		props: {
			title: { type: "string", role: "title", required: true },
			description: { type: "string", role: "description" },
			value: { type: "string", role: "value" },
			selected: { type: "boolean", role: "state", defaultValue: false },
			disabled: { type: "boolean", role: "state", defaultValue: false },
		},
	},
	OptionList: {
		type: "OptionList",
		kind: "option-list",
		source: "react-component",
		version: "1.0.0",
		description:
			"Option section wrapper for device detail screens, rendering repeated OptionCard selections.",
		aliases: ["option-list", "Local_OptionList", "OptionList"],
		props: {
			title: { type: "string", role: "title" },
			description: { type: "string", role: "description" },
			items: { type: "array", role: "data", defaultValue: [] },
			columns: {
				type: "enum",
				role: "layout",
				values: ["1", "2"],
				defaultValue: "2",
			},
			selectedId: { type: "string", role: "state" },
		},
	},
	ProductInfo: {
		type: "ProductInfo",
		kind: "product-info",
		source: "react-component",
		version: "1.0.0",
		description: "Product summary block for commerce detail hero sections.",
		aliases: ["product-info", "ProductInfoSummary"],
		props: {
			brand: { type: "string", role: "label" },
			title: { type: "string", role: "title", required: true },
			description: { type: "string", role: "description" },
			price: { type: "string", role: "value" },
			originalPrice: { type: "string", role: "value" },
			discountRate: { type: "string", role: "value" },
			badges: { type: "array", role: "data" },
		},
	},
	RadioText: {
		type: "RadioText",
		source: "react-component",
		version: "1.0.0",
		aliases: ["Radio", "radio"],
		props: {
			label: { type: "string", role: "label", required: true },
			checked: { type: "boolean", role: "state", defaultValue: false },
		},
	},
	StoreCard: {
		type: "StoreCard",
		kind: "store-card",
		source: "react-component",
		version: "1.0.0",
		description: "Nearby store list item for product detail patterns.",
		aliases: ["store-card", "StoreListItem", "nearby-store-card"],
		props: {
			title: { type: "string", role: "title", required: true },
			address: { type: "string", role: "description" },
			distance: { type: "string", role: "value" },
			status: { type: "string", role: "state" },
		},
	},
	SectionHeader: {
		type: "SectionHeader",
		kind: "section-header",
		source: "renderer-composite",
		version: "1.0.0",
		props: {
			title: { type: "string", role: "title", required: true },
			description: { type: "string", role: "description" },
		},
	},
	SectionMessage: {
		type: "SectionMessage",
		kind: "section-message",
		source: "renderer-composite",
		version: "1.0.0",
		aliases: ["section-message"],
		props: {
			variant: {
				type: "enum",
				role: "styleVariant",
				values: ["info", "negative", "positive", "cautionary"],
				defaultValue: "info",
				variantTokens: {
					info: { surface: "color.surface.elevated", text: "color.text", icon: "color.icon.brand" },
					negative: {
						surface: "color.surface.elevated",
						text: "color.text.error",
						icon: "color.icon",
					},
					positive: { surface: "color.surface.elevated", text: "color.text", icon: "color.icon" },
					cautionary: { surface: "color.surface.elevated", text: "color.text", icon: "color.icon" },
				},
			},
			title: { type: "string", role: "title" },
			message: { type: "string", role: "content" },
			description: { type: "string", role: "description" },
		},
	},
	Tab: {
		type: "Tab",
		source: "react-component",
		version: "1.0.0",
		description: "Top tab navigation strip for switching list categories.",
		aliases: ["tab", "tabs", "TabNavigation"],
		props: {
			items: { type: "array", role: "data", required: true },
			activeKey: { type: "string", role: "state", required: true },
		},
	},
	TextButton: {
		type: "TextButton",
		kind: "text-link",
		source: "react-component",
		version: "1.0.0",
		description:
			"Inline text button, including underline link and Figma ButtonMore affordance variants in PRDD specs.",
		aliases: [
			"ButtonTextUnderline",
			"button-text-underline",
			"text-button",
		],
		props: {
			label: { type: "string", role: "label", required: true },
			underline: { type: "boolean", role: "styleVariant", defaultValue: false },
		},
	},
	TextField: {
		type: "TextField",
		kind: "text-field",
		source: "react-component",
		version: "1.0.0",
		aliases: ["text-field", "text-area"],
		props: {
			label: { type: "string", role: "label" },
			placeholder: { type: "string", role: "description" },
			helperText: { type: "string", role: "description" },
			value: { type: "string", role: "value" },
			inputType: { type: "string", role: "data", defaultValue: "text" },
			state: {
				type: "enum",
				role: "state",
				values: ["default", "focused", "typing", "typed", "disabled"],
				defaultValue: "default",
			},
			error: { type: "boolean", role: "state", defaultValue: false },
			button: { type: "boolean", role: "styleVariant", defaultValue: false },
			buttonLabel: { type: "string", role: "label" },
			rightElement: { type: "node", role: "slot", aiWritable: false },
			type: { type: "string", role: "data" },
		},
	},
	SearchBar: {
		type: "SearchBar",
		kind: "search-bar",
		source: "react-component",
		version: "1.0.0",
		description: "Rounded search input with search and LLM action variants from SKT GenUI.",
		aliases: ["search-bar", "SearchInput", "SearchBarLLM"],
		props: {
			placeholder: { type: "string", role: "description", defaultValue: "검색" },
			value: { type: "string", role: "value" },
			variant: {
				type: "enum",
				role: "styleVariant",
				values: ["search", "llm"],
				defaultValue: "search",
			},
		},
	},
	TitleSection: {
		type: "TitleSection",
		kind: "title-section",
		source: "react-component",
		version: "1.0.0",
		description: "Section title row used by PRDD and SKT Next UI section stacks.",
		aliases: ["title-section", "ContentsTitle", "TextListGroupTitle"],
		props: {
			title: { type: "string", role: "title", required: true },
			subtitle: { type: "string", role: "description" },
			rightText: { type: "string", role: "label" },
			badge: { type: "string", role: "styleVariant" },
		},
	},
	ThumbnailLarge: {
		type: "ThumbnailLarge",
		kind: "thumbnail-large",
		source: "react-component",
		version: "1.0.0",
		description: "Large product visual block used at the top of commerce detail screens.",
		aliases: ["thumbnail-large", "hero-media", "ProductThumbnailLarge"],
		props: {
			src: { type: "string", role: "data" },
			alt: { type: "string", role: "description" },
			title: { type: "string", role: "title" },
			eyebrow: { type: "string", role: "label" },
			backgroundColor: { type: "string", role: "styleVariant" },
		},
	},
} as const satisfies ComponentCatalog;
